### ISSUE TITLE
widget does not display

### ISSUE THREAD

**Issue by HugoCornelis** [mrfoh/cordova-datepicker-plugin#2]
Great project!

I am new to cordova development and trying out this plugin with the 'time' mode.  Installation went fine but I cannot get it to work in the android emulator.  The datetime picker widget does not show up in the app.

I currently have html code like this in my app:

```
<button class="nativetimepicker">
  My native time picker.
</button>
```

I also tried this with <p> and <div> elements, with empty elements, but they all give the same result.

I also copied the unmodified javascript of the documentation to an appropriate location in the 'deviceready' callback in the index.js file.

Help appreciated, thanks.

**Comment by mrfoh** [comment]
Hello Hugo, glad you found the plugin useful. Unfortunately I have similar
issues with time mode of the plugin. Am not the original author of the
plugin. I ported it to Cordova 3.0.0.

**Comment by HugoCornelis** [comment]
Thanks for your quick answer.

The plugin now mysteriously does show up.  So I am sure I have done something stupid in my previous trials.

This is the relevant snippet of HTML code I am currently using:

```
<input name="timepicker" id="timepicker" readonly="1" class="nativetimepicker" />
```

With the same javascript as before.

Now I still have the problem with the timepicker only showing up once.  I saw the 'trick' for working with the 'date' mode.  I am still relatively naive regarding javascript, could you guess for a similar trick for the 'time' mode?

**Comment by mrfoh** [comment]
Am not anywhere close to my computer at the moment, but when I get back
I'll look at it.

**Comment by HugoCornelis** [comment]
I cannot remember what exactly I changed.  Now things work as expected.

So I close this issue.

Thanks for the help.

**Comment by karthikmanoharan** [comment]
Great work!

I do it in windows phonegap 3.4 but it is not working give me some suggestions

**Comment by mrfoh** [comment]
The plugin only works for android os 

Best regards
Patrick Foh

**Comment by karthikmanoharan** [comment]
Thanks for your reply,can you suggest me any plugin for android and windows please. i am using windows 8 phone gap

**Comment by mrfoh** [comment]
Check out the phonegap build service it has a lot of plugins for various platforms. You could also check UI frameworks like kendo UI, it may have the date picker component you could use. Good luck 

Best regards
Patrick Foh
